services:
  db:
    container_name: shadow-shop
    image: postgres:16.6
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./bd-data:/var/lib/postgresql/data
